# Generated by Django 5.1.7 on 2025-03-18 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
