# Generated by Django 5.1.7 on 2025-03-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='user',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
